services:
  elasticsearch:
    image: elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true # Enable security settings
      - ELASTIC_PASSWORD=password # Set elastic user password
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:8.2
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root # Set root user password
      - MYSQL_DATABASE=demo # Initial database name
      - MYSQL_USER=my_user # Initial database user
      - MYSQL_PASSWORD=my_user_password # Initial user password
    ports:
      - "3306:3306" # Map port 3306
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data

  postgresql:
    image: postgres:13.16
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres_user # Set PostgreSQL username
      - POSTGRES_PASSWORD=postgres_password # Set PostgreSQL user password
      - POSTGRES_DB=demo_db # Initial database name
    ports:
      - "5432:5432" # Map port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data # Persist PostgreSQL data

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DB=default # Default database
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  redis:
    image: redis:7.4
    container_name: redis
    command: ["redis-server", "--requirepass", "your_redis_password"] # Set password
    ports:
      - "6379:6379" # Map Redis default port
    volumes:
      - redis_data:/data # Persist Redis data
  
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user # Set MongoDB initial username
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password # Set MongoDB initial password
      - MONGO_INITDB_DATABASE=demo_db # Initial database name
    ports:
      - "27017:27017" # Map MongoDB default port
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  es_data:
    driver: local
  mysql_data:
    driver: local
  pg_data:
    driver: local
  clickhouse_data:
    driver: local
  redis_data:
    driver: local
  mongo_data:
    driver: local
