version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user # Set MongoDB initial username
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password # Set MongoDB initial password
      - MONGO_INITDB_DATABASE=demo_db # Initial database name
    ports:
      - "27017:27017" # Map MongoDB default port
    volumes:
      - mongo_data:/data/db # Persist MongoDB data


volumes:
  mongo_data:
    driver: local