http.host: "0.0.0.0"
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs
pipeline.ordered: false
config.reload.automatic: true
config.reload.interval: 3s
