services:
  jobmanager:
    image: flink:1.20.0-scala_2.12-java11
    container_name: flink_jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081" # Flink Web UI
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager"
    command: jobmanager

  taskmanager:
    image: flink:1.20.0-scala_2.12-java11
    hostname: taskmanager
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager"
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2 # Start 2 TaskManagers, you can adjust as needed

networks:
  default:
    driver: bridge
