services:
  mysql-metastore:
    image: mysql:8.2
    container_name: mysql-metastore
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=metastore
      - MYSQL_USER=hive
      - MYSQL_PASSWORD=hive_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_metastore_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=mysql
      - HIVE_METASTORE_DB_HOST=mysql-metastore
      - HIVE_METASTORE_DB_PORT=3306
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASSWORD=hive_password
    ports:
      - "9083:9083" # Hive Metastore port
    depends_on:
      - mysql-metastore
    command: "schematool -initSchema -dbType mysql && hive --service metastore"

  hive-server:
    image: apache/hive:3.1.3
    container_name: hive-server
    environment:
      - HIVE_SERVER2_THRIFT_PORT=10000
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    ports:
      - "10000:10000" # Hive Server2 port
    depends_on:
      - hive-metastore
    command: "hive --service hiveserver2"

volumes:
  mysql_metastore_data:
    driver: local