version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hivepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870" # Namenode Web UI
      - "9000:9000" # Namenode RPC
    volumes:
      - hadoop_namenode_data:/hadoop/dfs/name
    depends_on:
      - mysql

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    volumes:
      - hadoop_datanode_data:/hadoop/dfs/data
    depends_on:
      - namenode

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_DB_HOST=mysql
      - HIVE_METASTORE_DB_PORT=3306
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASSWORD=hivepassword
      - SERVICE_PRECONDITION="mysql:3306"
    depends_on:
      - mysql
      - namenode
    ports:
      - "9083:9083" # Hive Metastore port

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_SERVER2_THRIFT_PORT=10000
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000" # Hive Server2 port

volumes:
  mysql_data:
  hadoop_namenode_data:
  hadoop_datanode_data:
