services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-vector
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=mypassword
    command: >
      redis-server 
      --loadmodule /opt/redis-stack/lib/redisearch.so 
      --loadmodule /opt/redis-stack/lib/rejson.so 
      --protected-mode no 
      --requirepass mypassword
    networks:
      - redis-net

volumes:
  redis_data:

networks:
  redis-net:
    driver: bridge