version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus configuration file
      - prometheus_data:/prometheus                                  # Persist Prometheus data
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin         # Set Grafana default username
      - GF_SECURITY_ADMIN_PASSWORD=admin     # Set Grafana default password
    volumes:
      - grafana_storage:/var/lib/grafana      # Persist Grafana data
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    links:
      - prometheus                           # Ensure Grafana can access Prometheus

volumes:
  prometheus_data:
    driver: local
  grafana_storage:
    driver: local